module.exports = {
  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "Arterial Diseases",
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "arterial" }],
    },
    {
      type: "category",
      label: "Venous Diseases",
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "venous" }],
    },
    // (اختياري لاحقًا) Aneurysms / AVF / Trauma كـ categories منفصلة
  ],
};
