module.exports = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Arterial Diseases',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'arterial' }],
    },
  ],
};
